version: '3'

services:

  postgres:
    env_file: .env
    image: postgres:11-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  consul:
    image: consul:1.4.2
    ports:
      - "8500:8500"  # GUI
      - "8600:8600"  # DNS
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: consul agent -server -dev -ui -client 0.0.0.0

  vault:
    image: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -dev -dev-root-token-id="custom-token-change-me" -dev-listen-address="0.0.0.0:8200"

