spring:
  profiles:
    include:
      - local-inmem

  cloud:
    vault:
      enabled: false
    consul:
      enabled: false
      config:
        enabled: false


custom:
  welcome: "Hello"
  name: "Local User"
