spring:
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        default_schema: public
    open-in-view: false
    datasource:
      url: jdbc:postgresql://${PG_ADDRESS:localhost:5432}/${PG_DATABASE:postgres}
      username: ${PG_USERNAME:postgres}
      password: ${PG_PASSWORD:postgres}
      driverClassName: org.postgresql.Driver
